// ============================================
// Sentinel – Mock Data
// ============================================

import { Severity, Schedule, RegretRisk, ItemStatus, type WatchedItem } from "@/types/sentinel";
import { DEFAULT_CATEGORIES } from "./constants";
import { daysFromNow } from "./date-utils";

export const mockWatchedItems: WatchedItem[] = [
  {
    id: "1",
    title: "Renew car insurance policy",
    category: DEFAULT_CATEGORIES[3],
    severity: Severity.High,
    nextDate: daysFromNow(3),
    schedule: Schedule.Yearly,
    regretRisk: RegretRisk.High,
    actionWindow: "Best action window: 2–4 weeks before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-90),
  },
  {
    id: "2",
    title: "Annual dental checkup",
    category: DEFAULT_CATEGORIES[1],
    severity: Severity.Medium,
    nextDate: daysFromNow(8),
    schedule: Schedule.Yearly,
    regretRisk: RegretRisk.Medium,
    actionWindow: "Best action window: 1–2 weeks before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-180),
  },
  {
    id: "3",
    title: "Replace water filter cartridge",
    category: DEFAULT_CATEGORIES[2],
    severity: Severity.Low,
    nextDate: daysFromNow(12),
    schedule: Schedule.Monthly,
    regretRisk: RegretRisk.Low,
    actionWindow: "Best action window: 5–10 days before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-30),
  },
  {
    id: "4",
    title: "Passport renewal",
    category: DEFAULT_CATEGORIES[6],
    severity: Severity.High,
    nextDate: daysFromNow(18),
    schedule: Schedule.OneTime,
    regretRisk: RegretRisk.High,
    actionWindow: "Best action window: 3–6 months before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-60),
  },
  {
    id: "5",
    title: "Property tax quarterly payment",
    category: DEFAULT_CATEGORIES[4],
    severity: Severity.Medium,
    nextDate: daysFromNow(25),
    schedule: Schedule.Quarterly,
    regretRisk: RegretRisk.Medium,
    actionWindow: "Best action window: 1–2 weeks before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-120),
  },
  {
    id: "6",
    title: "Update emergency contacts list",
    category: DEFAULT_CATEGORIES[6],
    severity: Severity.Low,
    nextDate: daysFromNow(35),
    schedule: Schedule.Yearly,
    regretRisk: RegretRisk.Low,
    actionWindow: "Best action window: anytime this month",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-200),
  },
  {
    id: "7",
    title: "Home warranty expiration",
    category: DEFAULT_CATEGORIES[2],
    severity: Severity.Medium,
    nextDate: daysFromNow(45),
    schedule: Schedule.Yearly,
    regretRisk: RegretRisk.Medium,
    actionWindow: "Best action window: 30 days before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-300),
  },
  {
    id: "8",
    title: "Professional license renewal",
    category: DEFAULT_CATEGORIES[5],
    severity: Severity.High,
    nextDate: daysFromNow(60),
    schedule: Schedule.Yearly,
    regretRisk: RegretRisk.High,
    actionWindow: "Best action window: 60–90 days before",
    status: ItemStatus.Active,
    createdAt: daysFromNow(-180),
  },
];
